name: Extract Issue Info

on:
  issue_comment:
    types: [edited]

jobs:
  extract-info:
    runs-on: ubuntu-latest
    steps:
    - name: Get issue info
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const issueNumber = context.payload.issue.number;

          // Get issue data
          const issueData = await github.issues.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issueNumber
          });

          console.log("Issue Title:", issueData.data.title);
          console.log("Issue Body:", issueData.data.body);
          console.log("Issue Creator:", issueData.data.user.login);
          console.log("Issue data:", issueData.data)
          
          // Set outputs if needed
          // return {
          //   title: issueData.data.title,
          //   body: issueData.data.body,
          //   creator: issueData.data.user.login
          // };
