name: Require Checklist

on:
 pull_request_review:
    types: [submitted, approved]


jobs:
  tasks-check:
    name: Check tasks
    needs: review-checklist
    uses: ./.github/workflows/tasks-check.yaml