name: Tasks Check

on:
  workflow_call:
  pull_request:
    types: 
      - opened
  pull_request_review:
    types: 
      - submitted
      - approved
jobs:
  checkbox-check:
    runs-on: ubuntu-latest
    steps:
    - name: Check checkboxes
      uses: mheap/require-checklist-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        requireChecklist: true