name: Tasks Check Trigger

on:
  issue_comment:
    types: [edited]

jobs:
  extract-pr-number:
    if: (github.event.issue.pull_request != null && github.event_name == 'issue_comment') || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Extract PR number
        id: extract-pr
        run: echo "::set-output name=pr_number::$(jq --raw-output .issue.number "$GITHUB_EVENT_PATH")"

  tasks-check:
    if: (github.event.issue.pull_request != null && github.event_name == 'issue_comment') || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - name: Check checkboxes
      uses: mheap/require-checklist-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issueNumber: ${{ steps.extract-pr.outputs.pr_number }}

  update-pr-checks:
    if: (github.event.issue.pull_request != null && github.event_name == 'issue_comment') || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Create or Update Check
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const sha = context.eventName === 'pull_request' ? context.payload.pull_request.head.sha : context.payload.issue.pull_request.head.sha;
            const conclusion = "${{ steps.checklist-check.outcome }}" === 'success' ? 'success' : 'failure';
            const output = {
              title: 'Checkbox Check Result',
              summary: conclusion === 'success' ? 'All checkboxes are checked' : 'Some checkboxes are unchecked'
            };
            
            await github.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Checkbox Check',
              head_sha: sha,
              status: 'completed',
              conclusion: conclusion,
              output: output
            });
