name: Require Checklist

on:
  workflow_dispatch:
  workflow_call:
  issue_comment:
    types: [edited]

jobs:
  check-tasks:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      - uses: mheap/require-checklist-action@v2
        with:
          requireChecklist: true # If this is true and there are no checklists detected, the action will fail