name: Require Checklist

on:
  pull_request:
    types: 
      - opened
  pull_request_review:
    types:
      - submitted
      - approved

jobs:
  review-checklist:
    name: Make validation comment on PR
    permissions: write-all
    uses: ./.github/workflows/review-checklist.yaml

  tasks-check:
    name: Check tasks
    needs: review-checklist
    uses: ./.github/workflows/tasks-check.yaml
